<a href="https://colab.research.google.com/github/HoYoungChun/financial_data_analysis/blob/main/Magic_Formula(EV_EBITDA).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Basic Setting

In [ ]:
import pandas as pd
from tqdm import tqdm
from bs4 import BeautifulSoup
#import urllib.request
from urllib import request as rq

In [ ]:
FS_URL = 'https://comp.fnguide.com/SVO2/ASP/SVD_Finance.asp?pGB=1&gicode=A{}&cID=&MenuYn=Y&ReportGB=&NewMenuID=103&stkGb=701'
INDEX_URL = 'https://comp.fnguide.com/SVO2/ASP/SVD_Invest.asp?pGB=1&gicode=A{}&cID=&MenuYn=Y&ReportGB=&NewMenuID=105&stkGb=701'
sample_code = '005930'

### EV/EBITDA
Earnings(영업이익) before Interest(이자), Tax(법인세), Depreciation(유형자산 감가삼각), Amortization(무형자산 감가삼각)

In [ ]:
index_html = rq.urlopen(INDEX_URL.format(sample_code)).read()
index_soup = BeautifulSoup(index_html, 'html.parser')
ev_cells = index_soup.find('tr',{'id':'p_grid1_14'}).find_all('td',{'class':'r'})
ev = float(ev_cells[3].string.replace(',',''))

### Get Gross Profit

In [ ]:
fs_html = rq.urlopen(FS_URL.format(sample_code)).read()
fs_soup = BeautifulSoup(fs_html, 'html.parser')
gp_cells = fs_soup.find('div',{'id':'divSonikY'}).find_all('tr',{'class':'rwf'})
gross_profit = float(gp_cells[2].find_all('td')[2].string.replace(',',''))
gross_profit

923187.0

### Get Asset

In [ ]:
asset_cells = fs_soup.find('div',{'id':'divDaechaY'}).find_all('tr',{'class':'rwf'})
asset = float(asset_cells[0].find_all('td')[2].string.replace(',',''))
asset

3782357.0

### Get All Stock code

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [11]:
csv_url = '/content/drive/MyDrive/Colab/financial_data_analysis/company.csv'
company = pd.read_csv(csv_url, encoding='utf-8')
code_list = company['종목코드']
sample_code_list = code_list[1000:1050]
sample_code_list

1000    207930
1001    214270
1002    189690
1003    213420
1004    206660
1005    060480
1006    206640
1007    208640
1008    193250
1009    204630
1010    200470
1011    200670
1012    208710
1013    189860
1014    067390
1015    080580
1016    208350
1017    160550
1018    124500
1019    142280
1020    187220
1021    208370
1022    207720
1023    208140
1024    149980
1025    084650
1026    200710
1027    200780
1028    207760
1029    196170
1030    206400
1031    178920
1032    140520
1033    173940
1034    205470
1035    200230
1036    194510
1037    204840
1038    196490
1039    204620
1040    205500
1041    205100
1042    191420
1043    192440
1044    182690
1045    143540
1046    203650
1047    041920
1048    194480
1049    203690
Name: 종목코드, dtype: object

### Create Crawling Function

In [12]:
def crawler(li):
    #url setting
    FS_URL = 'https://comp.fnguide.com/SVO2/ASP/SVD_Finance.asp?pGB=1&gicode=A{}&cID=&MenuYn=Y&ReportGB=&NewMenuID=103&stkGb=701'
    INDEX_URL = 'https://comp.fnguide.com/SVO2/ASP/SVD_Invest.asp?pGB=1&gicode=A{}&cID=&MenuYn=Y&ReportGB=&NewMenuID=105&stkGb=701'

    result ={}
    for code in tqdm(li):
        try:
            index_html = rq.urlopen(INDEX_URL.format(code)).read()
            index_soup = BeautifulSoup(index_html, 'html.parser')
            fs_html = rq.urlopen(FS_URL.format(code)).read()
            fs_soup = BeautifulSoup(fs_html, 'html.parser')

            #get company name
            name = company[company['종목코드'] == code]['회사명'].values[0]

            #get EV/EBITA
            ev_cells = index_soup.find('tr',{'id':'p_grid1_14'}).find_all('td',{'class':'r'})
            ev = float(ev_cells[3].string.replace(',',''))

            #get Gross profit
            gp_cells = fs_soup.find('div',{'id':'divSonikY'}).find_all('tr',{'class':'rwf'})
            gross_profit = float(gp_cells[2].find_all('td')[2].string.replace(',',''))

            #get Asset
            asset_cells = fs_soup.find('div',{'id':'divDaechaY'}).find_all('tr',{'class':'rwf'})
            asset = float(asset_cells[0].find_all('td')[2].string.replace(',',''))

            #insert into result dict
            result[name]=[code, ev, gross_profit, asset]


        except(ValueError, AttributeError, IndexError, TypeError):
            pass
    
    # convert dict into DataFrame
    result_df = pd.DataFrame(result)

    # transposing DataFrame
    result_df = result_df.transpose()

    # set column names
    result_df.columns=['Code','EV_EBITDA','Gross_profit', 'Asset']
    
    return result_df

In [9]:
result_df = crawler(sample_code_list)
result_df

100%|██████████| 50/50 [01:47<00:00,  2.14s/it]

             Code EV_EBITDA Gross_profit Asset
퓨쳐스트림네트웍스  214270     13.47         1635  2129
포시에스       189690     11.41          160   570
덕산네오룩스     213420     18.55          536  2209
국일신동       060480     87.98           18   523
바디텍메드      206640      7.88          977  1635
하이셈        200470      8.08           99  1304
휴메딕스       200670      9.26          395  1756
바이오로그디바이스  208710     17.72           43  1011
서전기전       189860      7.26          141   561
오킨스전자      080580     35.88           94   583
지란지교시큐리티   208350     45.64          206  1042
NEW        160550    108.41          360  2758
아이티센       124500     13.95          922  5419
녹십자엠에스     142280     47.11          198  1056
디티앤씨       187220     10.56          246  1878
셀바스헬스케어    208370     15.45           98   451
정다운        208140     18.87          152  1515
하이로닉       149980     32.52           81   448
랩지노믹스      084650      3.71          717  1094
에이디테크놀로지   200710     26.53          239  2203
비씨월드제약     200780     34.69          238  1930
미스터블루      207760     15.38          807   703
알테오젠       196170   2560.91          188  1592
엔터메이트      206400    128.57           94   738
SKC코오롱PI   178920     13.32          847  4040
하이제2호스팩    205470     12.45          309   682
텔콘         200230    257.49           73  1851
파티게임즈      194510      1.69          667  1448
엑셈         205100     14.45          242   944
테고사이언스     191420    111.47           66   504
슈피겐코리아     192440      4.66         2738  4054
테라셈        182690     26.72           32   559
영우디에스피     143540     11.03          168  1039
드림시큐리티     203650      5.19          533  2817
메디아나       041920       8.1          266   768
프로스테믹스     203690    152.29           65   602

In [13]:
tmp_df = result_df.copy()
tmp_df.head(10)

             Code EV_EBITDA Gross_profit Asset
퓨쳐스트림네트웍스  214270     13.47         1635  2129
포시에스       189690     11.41          160   570
덕산네오룩스     213420     18.55          536  2209
국일신동       060480     87.98           18   523
바디텍메드      206640      7.88          977  1635
하이셈        200470      8.08           99  1304
휴메딕스       200670      9.26          395  1756
바이오로그디바이스  208710     17.72           43  1011
서전기전       189860      7.26          141   561
오킨스전자      080580     35.88           94   583

In [14]:
tmp_df['GP_A'] = tmp_df['Gross_profit'] / tmp_df['Asset']
tmp_df

             Code EV_EBITDA Gross_profit Asset       GP_A
퓨쳐스트림네트웍스  214270     13.47         1635  2129   0.767966
포시에스       189690     11.41          160   570   0.280702
덕산네오룩스     213420     18.55          536  2209   0.242644
국일신동       060480     87.98           18   523  0.0344168
바디텍메드      206640      7.88          977  1635   0.597554
하이셈        200470      8.08           99  1304  0.0759202
휴메딕스       200670      9.26          395  1756   0.224943
바이오로그디바이스  208710     17.72           43  1011  0.0425321
서전기전       189860      7.26          141   561   0.251337
오킨스전자      080580     35.88           94   583   0.161235
지란지교시큐리티   208350     45.64          206  1042   0.197697
NEW        160550    108.41          360  2758   0.130529
아이티센       124500     13.95          922  5419   0.170142
녹십자엠에스     142280     47.11          198  1056     0.1875
디티앤씨       187220     10.56          246  1878    0.13099
셀바스헬스케어    208370     15.45           98   451   0.217295
정다운        208140     18.87          152  1515    0.10033
하이로닉       149980     32.52           81   448   0.180804
랩지노믹스      084650      3.71          717  1094   0.655393
에이디테크놀로지   200710     26.53          239  2203   0.108488
비씨월드제약     200780     34.69          238  1930   0.123316
미스터블루      207760     15.38          807   703    1.14794
알테오젠       196170   2560.91          188  1592    0.11809
엔터메이트      206400    128.57           94   738   0.127371
SKC코오롱PI   178920     13.32          847  4040   0.209653
하이제2호스팩    205470     12.45          309   682   0.453079
텔콘         200230    257.49           73  1851  0.0394381
파티게임즈      194510      1.69          667  1448   0.460635
엑셈         205100     14.45          242   944   0.256356
테고사이언스     191420    111.47           66   504   0.130952
슈피겐코리아     192440      4.66         2738  4054   0.675382
테라셈        182690     26.72           32   559  0.0572451
영우디에스피     143540     11.03          168  1039   0.161694
드림시큐리티     203650      5.19          533  2817   0.189208
메디아나       041920       8.1          266   768   0.346354
프로스테믹스     203690    152.29           65   602   0.107973

### Grading Scores
#### 1. EV/EBITDA Score

In [15]:
top_range = int(len(tmp_df)*0.3)
middle_range = int(len(tmp_df)*0.7)

In [16]:
print(top_range, middle_range)

10 25

In [ ]:
#tmp_df[tmp_df['Code'].isin(tmp_df.sort_values(by='EV_EBITDA')[:top_range]['Code'])]
tmp_df.loc[tmp_df['Code'].isin(tmp_df.sort_values(by='EV_EBITDA')[:top_range]['Code']),'EV_EBITDA_Score'] = 3
tmp_df.loc[tmp_df['Code'].isin(tmp_df.sort_values(by='EV_EBITDA')[top_range:middle_range]['Code']),'EV_EBITDA_Score'] = 2
tmp_df.loc[tmp_df['Code'].isin(tmp_df.sort_values(by='EV_EBITDA')[middle_range:]['Code']),'EV_EBITDA_Score'] = 1
tmp_df

### GP/A Score

In [ ]:
#tmp_df.sort_values(by='GP_A', ascending=False)[:top_range]['Code']
#tmp_df['Code'].isin(tmp_df.sort_values(by='GP_A', ascending=False)[:top_range]['Code'])
tmp_df.loc[tmp_df['Code'].isin(tmp_df.sort_values(by='GP_A', ascending=False)[:top_range]['Code']),'GP_A_Score'] = 3
tmp_df.loc[tmp_df['Code'].isin(tmp_df.sort_values(by='GP_A', ascending=False)[top_range:middle_range]['Code']),'GP_A_Score'] = 2
tmp_df.loc[tmp_df['Code'].isin(tmp_df.sort_values(by='GP_A', ascending=False)[middle_range:]['Code']),'GP_A_Score'] = 1
tmp_df

In [ ]:
tmp_df['Total_Score'] = tmp_df['EV_EBITDA_Score'] + tmp_df['GP_A_Score']
tmp_df.sort_values(by='Total_Score', ascending=False)

In [29]:
max_point_df = tmp_df[tmp_df['Total_Score']==6.0]
max_point_df.sort_values(by='GP_A', ascending=False).head(30)

          Code EV_EBITDA Gross_profit  ... EV_EBITDA_Score GP_A_Score  Total_Score
슈피겐코리아  192440      4.66         2738  ...             3.0        3.0          6.0
랩지노믹스   084650      3.71          717  ...             3.0        3.0          6.0
바디텍메드   206640      7.88          977  ...             3.0        3.0          6.0
파티게임즈   194510      1.69          667  ...             3.0        3.0          6.0
메디아나    041920       8.1          266  ...             3.0        3.0          6.0

[5 rows x 8 columns]